# Generated by Django 4.2 on 2023-04-07 17:19

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_video_timestamp_video_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2023, 4, 7, 17, 19, 9, 90957, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
